name: Run testCode

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Start xcode build 🛠
        run: |
          xcodebuild clean test -project OdockOdock/OdockOdock.xcodeproj -scheme OdockOdock -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=latest'
